### ISSUE TITLE
error on triton_cross_scan_flex_k2

### ISSUE THREAD

**Issue by duan-song** [lewandofskee/MobileMamba#3]
When I use the MobileMamba as backbone to extract multi-scale features, some errpr occurred, as follow:
Traceback (most recent call last):
  File "<string>", line 21, in triton_cross_scan_flex_k2
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-14de7de5c4da5794c8ca14e7e41a122d-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float32, torch.float32), (0, 0, 0, 0, 2, 1, 32, 32, 320, 14, 14, 1, 1), (True, True))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train(train_loader, model, optimizer, epoch, save_path)
  File "train.py", line 160, in train
    pre, texture_pre, semantic_pre = model(images,depth)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/CPNet.py", line 340, in forward
    rgb1, rgb2, rgb3, = self.rgb_mobile(x)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 445, in forward
    x = self.blocks1(x)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 372, in forward
    x = self.ffn1(self.dw1(self.mixer(self.ffn0(self.dw0(x)))))
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 277, in forward
    return x + self.m(x)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 347, in forward
    x = self.attn(x)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 332, in forward
    x1 = self.global_op(x1)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/mobilemamba/mobilemamba.py", line 132, in forward
    x = self.base_scale(self.global_atten(x))
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/lib_mamba/vmambanew.py", line 574, in forwardv2
    y = self.forward_core(x)
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/lib_mamba/vmambanew.py", line 518, in forward_corev2
    xs = cross_scan_fn_k2(x, in_channel_first=True, out_channel_first=True, scans=_scan_mode,
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/lib_mamba/csm_tritonk2.py", line 746, in cross_scan_fn_k2
    return CSF.apply(x, in_channel_first, out_channel_first, one_by_one, scans)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/media/gpu/dss/code/SOD/SR-Mamba/SRMamba/models/MobileMamba/lib_mamba/csm_tritonk2.py", line 668, in forward
    triton_cross_scan_flex_k2[(NH * NW, NC, B)](
  File "<string>", line 41, in triton_cross_scan_flex_k2
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/triton/compiler.py", line 1621, in compile
    next_module = compile(module)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/triton/compiler.py", line 1550, in <lambda>
    lambda src: ast_to_ttir(src, signature, configs[0], constants)),
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/triton/compiler.py", line 962, in ast_to_ttir
    mod, _ = build_triton_ir(fn, signature, specialization, constants)
  File "/home/gpu/anaconda3/envs/dsspy/lib/python3.8/site-packages/triton/compiler.py", line 942, in build_triton_ir
    raise CompilationError(fn.src, node) from e
triton.compiler.CompilationError: at 33:74:
def triton_cross_scan_flex_k2(
    x, # (B, C, H, W) | (B, H, W, C) | (B, 4, C, H, W) | (B, H, W, 4, C)
    y, # (B, 4, C, H, W) | (B, H, W, 4, C)
    x_layout: tl.constexpr,
    y_layout: tl.constexpr,
    operation: tl.constexpr,
    onebyone: tl.constexpr,
    scans: tl.constexpr,
    BC: tl.constexpr,
    BH: tl.constexpr,
    BW: tl.constexpr,
    DC: tl.constexpr,
    DH: tl.constexpr,
    DW: tl.constexpr,
    NH: tl.constexpr,
    NW: tl.constexpr,
):
    i_hw, i_c, i_b = tl.program_id(0), tl.program_id(1), tl.program_id(2)
    i_h, i_w = (i_hw // NW), (i_hw % NW)
    _mask_h = (i_h * BH + tl.arange(0, BH)) < DH
    _mask_w = (i_w * BW + tl.arange(0, BW)) < DW
    _mask_hw = _mask_h[:, None] & _mask_w[None, :]
    _for_C = min(DC - i_c * BC, BC)

    HWRoute0 = i_h * BH * DW  + tl.arange(0, BH)[:, None] * DW + i_w * BW + tl.arange(0, BW)[None, :]
    HWRoute2 = (NH - i_h - 1) * BH * DW  + (BH - 1 - tl.arange(0, BH)[:, None]) * DW + (NW - i_w - 1) * BW + (BW - 1 - tl.arange(0, BW)[None, :]) + (DH - NH * BH) * DW + (DW - NW * BW) # flip

    if scans == 1:
        HWRoute2 = HWRoute0

    _tmp1 = DC * DH * DW

    y_ptr_base = y + i_b * 2 * _tmp1 + (i_c * BC * DH * DW if y_layout == 0 else i_c * BC)
                                                                          ^
Can you help me to address this issue?

**Comment by lewandofskee** [comment]
Please verify if the triton library is correctly installed. My current version of triton is 2.1.0. Please try running `pip3 install triton==2.1.0`. If you encounter any issues, please let me know. Thank you.

**Comment by duan-song** [comment]
Thank you very much. After running pip3 install triton==2.1.0, I solved the above problem
